### PR TITLE
Use the input container instead of results container

### PR DESCRIPTION
**Pull request by benjay10**
Instead of searching for the results container of the previous task in the flow, search for the input container of the diff task.

The tasks in the flow could change. For example, I'm trying to introduce a task that adds data to the model between mirroring and diff, so on consecutive updates to the same document, the diff service should pick up the file after the newly introduced task to calculate the most correct changes. The diff service was written to always look for the mirroring task's results. This hard codes the flow of tasks. By looking for the *input* file of the diff service, you take the result file from whatever previous task in the flow.

### CODE REVIEW

**Review by nbittich — CHANGES_REQUESTED** [review]
- Can you change the filename to `get-previous-input-container.sparql` ?
- then can you replace "getPreviousResultContainer" to "getPreviousInputContainer" here => https://github.com/lblod/harvesting-diff-service/blob/master/src/main/java/lblod/info/datasetdiff/TaskService.java#L104

**Comment by benjay10** [comment]
Ah yes of course!

**Comment by nbittich** [comment]
> Ah yes of course!

Also rename the file contains the query otherwise the query will not be loaded 🙂

**Comment by nbittich** [comment]
Nvm I didn't see the change, looks 👍

**Review by nbittich — APPROVED** [review]

**Pull request merged**
